services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_dev
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations
    restart: unless-stopped
    environment:
      - PB_DEV=true
    command: ["serve", "--http=0.0.0.0:8080", "--dev", "--origins=*"]

  app_dev:
    image: ghcr.io/cirruslabs/flutter:stable
    container_name: doorlock_app_dev
    working_dir: /app
    volumes:
      - ./app:/app
      - flutter_pub_cache:/root/.pub-cache
    ports:
      - "8090:8090"
    environment:
      - POCKETBASE_URL=http://localhost:8080
    depends_on:
      - pocketbase
    stdin_open: true
    tty: true
    command: |
      bash -c "
        echo 'Setting up Flutter development environment...'
        
        # Use offline mode if network issues occur
        echo 'Installing dependencies...'
        if ! flutter pub get; then
          echo 'Network issues detected, trying offline mode...'
          flutter pub get --offline || flutter pub get --no-precompile
        fi
        
        echo 'Starting Flutter development server...'
        # Try to start the server, handling potential network issues gracefully
        if ! flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8090; then
          echo 'Web development server failed to start due to network issues.'
          echo 'This is likely due to temporary network connectivity problems.'
          echo 'Try running the container again later or use local Flutter installation.'
          exit 1
        fi
      "

volumes:
  flutter_pub_cache: