#!/bin/bash
# Install Flutter SDK for local development

set -e

echo "🐦 Flutter SDK Installation Guide"
echo ""
echo "Due to network restrictions, automatic Flutter installation is not available."
echo "Please follow these manual steps to install Flutter:"
echo ""
echo "1. Download Flutter SDK:"
echo "   Visit: https://docs.flutter.dev/get-started/install/linux"
echo "   Or use this direct link: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.1-stable.tar.xz"
echo ""
echo "2. Extract to /tmp/flutter:"
echo "   tar xf flutter_linux_*-stable.tar.xz"
echo "   mv flutter /tmp/flutter"
echo ""
echo "3. Add to your PATH:"
echo "   export PATH=\"/tmp/flutter/bin:\$PATH\""
echo ""
echo "4. Verify installation:"
echo "   flutter doctor"
echo ""
echo "🐳 Alternative: Use Docker-based development"
echo "   The development scripts will automatically use Docker if Flutter is not available locally."
echo ""
echo "📋 After installation, you can run:"
echo "   cd app && flutter pub get"
echo "   cd app && flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8090"
echo ""