name: Doorlock Development Environment

on:
  workflow_call:
    inputs:
      copilot_agent_env:
        required: false
        type: string
    secrets:
      COPILOT_AGENT_API_KEY:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      POCKETBASE_URL: "http://localhost:8080"
      COPILOT_AGENT_ENV: ${{ inputs.copilot_agent_env }}
      COPILOT_AGENT_API_KEY: ${{ secrets.COPILOT_AGENT_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install Flutter dependencies
        run: |
          cd ${{ github.workspace }}/app
          flutter pub get

      - name: Set up Docker environment
        run: |
          docker --version
          docker compose version

      - name: Customize Copilot Agent Environment
        if: ${{ env.COPILOT_AGENT_ENV != '' }}
        run: |
          echo "${COPILOT_AGENT_ENV}" > ${{ github.workspace }}/copilot-agent.env
          cat ${{ github.workspace }}/copilot-agent.env
