name: Validate Environment Setup

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/copilot-setup-steps.yml'
      - 'scripts/validate-setup.sh'
      - 'app/pubspec.yaml'

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter (test version)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
          cache: true

      - name: Verify Flutter/Dart compatibility
        run: |
          flutter --version
          dart --version
          
          # Test version check logic
          DART_VERSION=$(dart --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Detected Dart version: $DART_VERSION"
          
          MAJOR=$(echo $DART_VERSION | cut -d. -f1)
          MINOR=$(echo $DART_VERSION | cut -d. -f2)
          if [[ $MAJOR -gt 3 ]] || [[ $MAJOR -eq 3 && $MINOR -ge 8 ]]; then
            echo "✅ Dart version $DART_VERSION meets requirement ^3.8.1"
          else
            echo "❌ Dart version $DART_VERSION does not meet requirement ^3.8.1"
            exit 1
          fi

      - name: Test Flutter dependencies
        run: |
          cd app
          flutter pub get
          echo "✅ Dependencies resolved successfully"

      - name: Test Flutter commands
        run: |
          cd app
          flutter analyze --no-fatal-infos
          echo "✅ Flutter analyze completed"

      - name: Test validation script
        run: |
          chmod +x scripts/validate-setup.sh
          # Run validation in test mode (skip PocketBase checks)
          SKIP_POCKETBASE=1 ./scripts/validate-setup.sh || echo "⚠️ Validation completed with warnings"

      - name: Environment summary
        run: |
          echo "=== Final Environment Summary ==="
          echo "Flutter: $(flutter --version | head -1)"
          echo "Dart: $(dart --version | head -1)"
          echo "Pubspec SDK requirement: $(grep -A 1 'environment:' app/pubspec.yaml | grep 'sdk:' | awk '{print $2}')"
          echo "✅ Setup validation completed successfully"