name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'

      - name: Install Flutter dependencies
        run: |
          cd ${{ github.workspace }}/app
          flutter pub get

      - name: Run static analysis
        run: |
          cd ${{ github.workspace }}/app
          flutter analyze

      - name: Run integration tests
        run: |
          cd ${{ github.workspace }}
          ./scripts/run_integration_tests.sh